### ISSUE TITLE
Make HTTP methods optional

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypub#18]
We should make one or the other of the ways to update an object optional -- either by posting an "edit" activity, or by doing an HTTP PUT.

I'd prefer that the PUT method (and similarly the DELETE) be optional. With pump.io, it's rarely used.

**Comment by cwebber** [comment]
Optional, or remove altogether from the spec?

We agreed in a meeting that GET and POST were the official ways forward in the spec, so I suggest we cut the other verbs out entirely.  That doesn't have to break pump.io... it's client to server behavior only anyway I think so pump.io can quietly support this legacy behavior, but for new applications going forward, it will be out of spec.  WDYT?

I'm planning to update the spec to this direction accordingly.
