### ISSUE TITLE
Submitting a file (e.g. a Photo)

### ISSUE THREAD

**Issue by xray7224** [w3c-social/activitypub#23]
It seems the specification doesn't cover submitting a file for example a photo. We ought to.

**Comment by cwebber** [comment]
Some decision needs to be made on whether we can do this all as one post or whether it needs multiple posts.

**Comment by cwebber** [comment]
I see work has been done on this in b54b49b9a2e265ef2f1237ea9f56387650a372f8 which is super-ultra-great!

One concern though: it mentions the "file endpoint" and that's undefined??

**Comment by cwebber** [comment]
This one's a bit trickier, because the file endpoint is not useful to anyone other than the actor/author, so it's not clear that it makes sense to expose it generally on the Actor object the way we expose inbox/outbox/following/followers...

It might be possible to reuse the inbox endpoint also for this when submitting multipart form data that is *not* encoded as json-ld activitystream, but that could have its own issues.

**Comment by cwebber** [comment]
@xray7224 I don't know what to do here.  Where do you think the file endpoint should be specified?  (Keep in mind also sandro's assertion in #59 that the binary section may already contain too much.)

**Comment by xray7224** [comment]
So yeah this could be done by just a generic upload link not on the actor's URLs something like:

https://example.tld/uploads

This allows uploads to be made by anyone and isn't exposed on a /actor/uploads type situation. I'm not sure what's best here.

**Comment by jaywink** [comment]
I suspect this use case is only for client to server not server to server? How does the spec specify what endpoints are relevant for delivering content or authoring content?

**Comment by cwebber** [comment]
@jaywink You're right, it's only client to server only.  The difference is that the public endpoints (inbox / outbox) are used for *both* client to server "authoring" *and* for federated communication (other users can post to your inbox or read from your outbox and get certain content).  The difference here is that it has no use for anyone other than the uploader in this case.

**Comment by cwebber** [comment]
@xray7224 That can be done, but where is the endpoint discovered?  A fixed URL is not ideal for our spec.  We intend to have more flexible methods of discovery for the other endpoints by looking up based on the user.

But I think your (what I think is your) general point is right: there's no need to tie to an API url per-user here.

**Comment by cwebber** [comment]
F2F resolution: It's okay to put the static upload endpoint on the user's profile object.

**Comment by cwebber** [comment]
I think I've properly addressed this with the last few commits.
