### ISSUE TITLE
Special "Followers" collection section incomplete

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypub#27]
[Missing documentation on the "followers" container](http://w3c-social.github.io/activitypump/#followers).  This is highly likely very similar to the special ["public" collection object](http://w3c-social.github.io/activitypump/#public-addressing)

**Comment by tsyesika** [comment]
This needs some wording changed for example, this needs removing:

> This is the default recipient list for otherwise unaddressed activities, and additionally is used as a distribution target for any activities addressed to the public.

We also need to explain what the use case is for this collection. Explain how this collection is built up and how it should be used.
