### ISSUE TITLE
How to define side effects in extensions?

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/activitypub#31]
Currently draft defines side effects for 7 Activities
http://w3c-social.github.io/activitypump/#activities

AS2 vocabulary draft currently defines 45 Activities
http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#activity-types e.g Read, Listen, Watch etc.

plus we need to anticipate people defining all kind of new types of activities - Eat, Drive etc. (e.g. http://aaronparecki.com/metrics)

From current draft
>6.3 Favorites Collection
>Every actor may have a favorites collection. This is a list of every object that the actor has favorited (See )
http://w3c-social.github.io/activitypump/#favorites

>8.2.6 Favourite or Like Activity
>The Favorite and Like activities are synonyms. These are used to add the actor to list of users who have liked or favorited the object.
http://w3c-social.github.io/activitypump/#favorite-like-activity

They in IMO bit vague way define side effect of Favourite/Like Activity as adding its object to 'Favorites Collection'.  As well as possibly some kind of 'Favoritings Collection' of that object. On my personal websites I publish events i attend, places i visit, organizations i stay affiliated with, products and services i offer and demand etc. Generic way of describing side effects of activities, in terms of relationships to various collections would come helpful. As of now this draft gives me impression of a recipe for making a clone of twitter without guidelines for extending such very minimal functionality.

**Comment by akuckartz** [comment]
Can the side effects be specified using Semantic Web rules ([SPIN](http://spinrdf.org/) ?) ?

**Comment by bblfish** [comment]
Direct and Indirect Containers have side effects. There may be something that can be done with that very simple structure.

**Comment by rhiaro** [comment]
+1 extensible side effect definitions, -1 using semantic web rules :)

**Comment by cwebber** [comment]
Here's my thinking: ActivityPump is defining, mostly, to the core vocabulary of ActivityStreams.  Within that, side effects are well understood.  Outside of that you're in the extension zone.  Activities which are not understood, generally, are ignored.  So if server A sends server B a "FoodFight" activity which is some food fighting game activity, and server B has no idea what that is, server B ignores it.

For defining vocabulary that's outside of the general activities, I think extension documents can be written, but in general I assume two servers implementing the same extension vocabulary should know how they both know how to use it.  I think it doesn't need to be handled in ActivityPump.

Given that, I'm inclined to add a section mentioning extensions, and say that for vocabulary defined outside of the standard ActivityStreams vocabulary, it's up to servers implementing those vocabulary extensions to coordinate how those extensions work.  I don't think a formal *technical* mechanism needs to exist beyond the vocabulary extension mechanism we have; a normative recommendation to publish documents explaining the intended effects of vocabulary extensions should cover the rest.

Thoughts?

**Comment by tsyesika** [comment]
We should add a section describing the side-effects of the activities used in ActivityPub core. I don't think that we need to define a mechanism for extensions to define their side-effects. Those who define extensions can describe side-effects in their own documents.

**Comment by cwebber** [comment]
We have sections describing side effects now, for both client to server and server to server.  I think that qualifies enough based on @xray7224's comment to close this.

**Comment by akuckartz** [comment]
Is @elf-pavlik satisfied with this resolution?
