### ISSUE TITLE
Transient and garbage collectable activities

### ISSUE THREAD

**Issue by cwebber** [w3c-social/activitypub#34]
The current drafting of ActivityPump more or less requires that any objects or activities must be preserved (or at minimum, a shell of them must be preserved) forever.  This comes from two things:

 - The requirement to de-duplicate incoming activities means that all activities must have URIs.  Theoretically one could use urn:uuid: identifiers as ids, but
 - The requirement to dereference activities/objects/etc and verify that they exist to prevent spoofing attacks means that the URIs must be something dereferencable such as HTTP

However, having some activities and objects be "transient" or garbage collectable is desirable:
 - Some kinds of social activities, such as playing games ("you hit the goblin!  you hit the goblin!") generate many very small activities.  Propagating these may be worthwhile, but keeping them around might not be.
 - There are privacy concerns related to some kinds of private communication and direct messaging which are "off the record".  Keeping these logged forever can be harmful to users who expect plausible deniability.

**Comment by akuckartz** [comment]
The two reasons at the end might be solvable by different means. In other words: these are two issues, not one.

**Comment by cwebber** [comment]
After the face to face conversation we had in San Francisco, I'm further convinced that they're related.

**Comment by cwebber** [comment]
Here's a suggestion on how to handle these which I have been considering.  I haven't considered all the edge cases.

Activities and objects may be delivered to a recipient which have no `@id`, or where the `@id` scheme is of `uuid:`.  The receiving server validates that all objects in the activitystreams object which lack an @id and object came from the same server / are of same origin.

This object will never be referenced by any later activity because it can't be verified after it's sent.  (It can't be reliably liked in a public feed, etc.)

What do people think of this idea?

**Comment by xray7224** [comment]
I can't think of an example off the top of my head but i suspect this will be too limited. I can imagine social networks where you would want a video or picture be posted and have people interact with it but after a set period of time the object expires and is no longer visible.

One way to do this would be to have a `expiry` as a date on the object and then have it in the spec that objects which interact with it should take the same `expiry` date. 

There is also another edge case not covered here. I'm wondering how a social platform such as snapchat would be able to adopt this API, it seems too limiting, even with my suggestion. Snapchat seems to work by a user posts a video and after 24 hours the video expires and is no longer visable. If the user however plays the video within that 24 hours, that video should expire for that person. I have no idea how to handle that in AP however if we're proposing a specification which is suppose to be flexible enough for new social networks to adopt it, we probably should know how snapchat could express what they want to do via our protocol.

**Comment by jaywink** [comment]
> I can't think of an example off the top of my head but i suspect this will be too limited. I can imagine social networks where you would want a video or picture be posted and have people interact with it but after a set period of time the object expires and is no longer visible.

Expiry is already a thing in some servers - for example Hubzilla (previously Redmatrix), allows setting an expiry on items. But, to be honest, isn't this more to do with content attributes via some AS2 extension for example rather than API/protocol?

Another consideration towards garbage collection can come from pure house keeping. Some larger diaspora* pods already do this simply because they want to offer maximum performance to current users and thus are happy to purge ancient items from years back, even if that means the object is "just gone". Especially if the item originates from another server.

I wouldn't personally worry too much about defining how to keep items forever or making it a must. If an item cannot be found then it is removed. That is how the internet works :)

**Comment by cwebber** [comment]
> I wouldn't personally worry too much about defining how to keep items forever or making it a must. If an item cannot be found then it is removed. That is how the internet works :)

@jaywink It's trickier in activitypump's case because objects can refer to other objects, and there's a verifiability problem.  I guess part of the reason things get so tricky verification-wise is that activitystreams objects often include the whole activity.  (That turns out to not be helpful in server to server anyway because the server needs to verify that the content being referenced is really what the server says it is. (It is helpful on server to client)).  One way or another, you have to make sure that a URI really exists.

**Comment by cwebber** [comment]
Oops, closing was an error.

**Comment by cwebber** [comment]
@xray7224 So, to reply to you, there's a couple of ways of doing things being proposed:

* Email/XMPP style: the message is delivered once, but then never needs to be stored by the originating server again.  I think you pointed out though, "what if it references a video, a-la snapchat", which leads us to...
* Expiration. This means the object remains on-server, referencable, for a certain period of time.  Of course, for all the reasons that transient activities are possibly complex to implement, this maybe gets *more* complicated when it comes to verification, because then the object disappears and *never leaves a tombstone* (because that's the goal here).

It seems like the real value of the expiration approach as opposed to the "non-referenceable `@id` approach" is for binary / out of band data.  Eg, images, videos, etc, which are not transferred across the graph by default in activitypump (and aren't in the default payload for certain).  These are the things that we might want to expire.

What if we limited expiration as a feature for certain kinds of binary data?

**Comment by cwebber** [comment]
F2F discussion: we won't support id-less notificaitons.  Clarify that it's up to servers if they want to keep around objects as long as they want.  If they want to delete objects, like maybe delete a bunch of game notifications, that's a-ok.

Perhaps a future extension will permit clarifying how long users might expect they can continue to access data.

**Comment by tsyesika** [comment]
After further discussion on this topic, we have decided a non-normative note would be useful to advise how transient activities could be achieved but OTR messaging is out of scope.

**Comment by tsyesika** [comment]
We could have transient activities that have ID's are otherwise regular objects but the server is fine to garbage to collect them as soon as they like and not include a tombstone. The server doesn't even have to store them in their database, they could simply store them in a cache or whatever. This is based off the discussion in the WG that suggested that deleted objects could GC whenever they like and simply return 404's.

**Comment by cwebber** [comment]
Closed, see 95b596f for details.
