### ISSUE TITLE
Simplifying deleted object tombstones

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypub#36]
Could we drop `@type`, `published` and `updated` from the deleted object tombstone (since `published` and `updated` are reset to the `deleted` date anyway) to 'delete' as much as possible?

**Comment by xray7224** [comment]
I agree "published" and "updated" are misleading especially given they're not when the object was published or updated.

**Comment by cwebber** [comment]
Jessica and I have discussed simply moving towards returning a 410 response instead of a shell object (though a shell object could optionally be delivered as well) for the things that currently have tombstones.  How would people feel about this?

**Comment by dmitrizagidulin** [comment]
Wait, how are you going to implement a 410 response if not by using a tombstone object?

**Comment by dmitrizagidulin** [comment]
Ah, I think you're talking about using 410 instead of _delivering_ tombstones, not instead of having tombstones at all. Am I reading that right?

**Comment by cwebber** [comment]
@dmitrizagidulin Yes that's right.  The equivalent of delivery will be by the "Deleted a note" and dump a super minimalist activity in there that probably just includes the @id, which you could indeed consider to be a tombstone.

**Comment by dmitrizagidulin** [comment]
Makes sense. As mentioned at lunch today at the F2F, I think a `deleted` property would be very useful for these tombstones -- hence https://github.com/jasnell/w3c-socialwg-activitystreams/issues/292

**Comment by cwebber** [comment]
There's a lot clearer information about deleting and optional Tombstone objects in the spec now.
