### ISSUE TITLE
DELETE method doesn't mention tombstone post

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypub#40]
Does this suggest that if you delete an object using HTTP DELETE there is no tombstone post left? Or does this just need adding/clarifying?

But if you post a `Delete` activity:

> "This MUST leave a shell of the object that will be displayed in activities which reference the deleted object"

**Comment by bblfish** [comment]
Well the `Tombstone object` could just be the message that comes with [HTTP's `410 Gone` code](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

**Comment by xray7224** [comment]
Amy you're right the object isn't properly deleted but actually a "shell" or tobstone remains, this ought to be clarified.

**Comment by bblfish** [comment]
Well why bother with a tombstone object when HTTP gives you `410`. I'd suggest aligning with HTTP.

**Comment by xray7224** [comment]
We produce a 410 also, the tombstone is for where the object is referenced in other activities, deleting an object doesn't delete the other activities from you and other people so a "shell" or "tombstone" is left in that place.

**Comment by kevinmarks** [comment]
Replacing the object with a tombstone is also a good way to ensure that other copies are flushed in replication.

**Comment by cwebber** [comment]
As per the last Face to Face meeting, we've agreed that Tombstones are not required, and are totally dependent upon particular implementation and its goals, and not having one is acceptable.  However, we should provide guidance on how to do the tombstone.

However we should coordinate with whatever the resolution of 
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/292#issuecomment-197935286
becomes.

**Comment by tsyesika** [comment]
HTTP methods will be removed as of #18, the delete verb as pointed out does cover what to do with tombstones however that is likely to change given the activity streams 2.0 (see [#292](https://github.com/jasnell/w3c-socialwg-activitystreams/issues/292)), that will be dealt with in #36.
