### ISSUE TITLE
The context

### ISSUE THREAD

**Issue by jasnell** [w3c-social/activitypub#43]
In several of the examples in the spec, we see:

```
"@context": [
    "http://www.w3.org/ns/activitystreams",
    "http://www.w3.org/ns/activitypump"
  ]
```

Listing both is actually not necessary. The activitypump context document can import the activitystreams context document itself...

http://www.w3.org/ns/activitypump:
```
{
  "@context": [  
    "http://www.w3.org/ns/activitystreams",
    {
      // activitypump definitions 
    }
  ]
}
```

Done this way, `activitypump` implementations only have to list `http://www.w3.org/ns/activitypump` and things will just work.

**Comment by cwebber** [comment]
Do we even need an activitypump context?  Might activitystreams provide all we need?

**Comment by cwebber** [comment]
It would be good to spec out what things might be needed that aren't provided by activitystreams (maybe inbox/outbox endpoints?) to determine if this is needed.

**Comment by xray7224** [comment]
We probably don't so we should update the examples for now, if we do need a context ourself we should add it then.

**Comment by elf-pavlik** [comment]
I suggest trying all the examples in http://json-ld.org/playground/
AS2.0 doesn't define: *outbox*, *inbox*, *followers*, *followings*, *preferredUsername*... one can just compare used terms with http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html

**Comment by cwebber** [comment]
I see that #22 references special properties are being added here.

**Comment by cwebber** [comment]
Sorry, I meant #30, augh

**Comment by xray7224** [comment]
We're not sure how to create a W3C namespace for a context. Can you help with this @sandhawke

**Comment by tsyesika** [comment]
We'll remove it from the examples and will specify it in the context when we have one.

**Comment by cwebber** [comment]
This is added to the [activitypub-context.jsonld file](https://github.com/w3c-social/activitypub/blob/gh-pages/activitypub-context.jsonld) included in this repository.  We still need to make this public somewhere, but that's what issue #30 is for.
