### ISSUE TITLE
Sending replies up the chain

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypub#47]
It's not clear how replies to replies are propagated to the original object.

http://w3c-social.github.io/activitypump/#notification-and-delivery: 

> Notification is the process of propagating awareness of the new activity to the activity's origin server such that the origin can act upon the activity (for example, notification that a user has liked an object is used to update the object's like count) and distribute the activity to ensure that it is propagated to the whole social graph which received the original object.... An object notified of an activity must deliver that activity to all recipients of the object 

If B is a reply to A, B's server sends B to A, and A sends B to A's recipients.

```
[ B ] ---> [ A ] ---> A's recipients
```

If C is a reply to B, C's server sends C to B, and B sends C to B's recipients.

```
[ C ] ---> [ B ] ---> B's recipients
```

...but... does B also send C to A's recipients? Since A's recipients were technically also recipients of B - "which received the original object", and B knows it was sent on to them?

```
[ C ] ---> [ B ] ---> B's recipients, A's recipients
```

Or does B send C to A, and A takes care of sending C to A's recipients?

```
[ C ] ---> [ B ] ---> B's recipients, [ A ] ---> A's recipients
```

Or does the propagation of C stop at B's recipients? This would mean viewers of A can only see one level of replies/comments, rather than threaded replies, or replies to replies (to replies to replies..) because A never knows about them. 

...I hope that makes sense.

**Comment by xray7224** [comment]
I think you might be right regarding the ambiguity. The way I think the way this should work would be that each object is responsible for updating the recipients they have federated to and the sender of the object if it wasn't them. This applied to your scenario would be:

1. `C` sends reply to `B`
2. `B` sends reply `C` to any additional audience from `A`'s original recipient set (if any)
3. `B` then sends reply `C ` to `A`
4. `A` then sends out `C` to the recipients `A` was sent to

I hope that makes sense, I can try and clarify tomorrow if it doesn't when it's not 01:31 ;) This also should be cleared up in the spec.

**Comment by csarven** [comment]
I think there may be a parallel concern here which has to do with multiple-replies. Can `C` reply-to both `B` and `A`, and perhaps also to `X` which is not part of `A`?

**Comment by rhiaro** [comment]
Thanks Jessica, I think I agree if s/A/B in 2. unless I'm reading it wrong.

If `C` is in reply to `B` and `A` and `X` wouldn't `C` just send it's
notifications as normal, and someone might have to to de-dup but nothing
out of the ordinary? There would be an interesting ux challenge with
displaying `A` plus replies of course.
