### ISSUE TITLE
Clarify normative reqs of default recipient list

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#51]
One place in spec says default list 'is' followers.
Later it says this is implementation specific and 'MAY'

https://hypothes.is/a/TXzYw_OvTi-gDK9eUqUyVQ

**Comment by cwebber** [comment]
You mean for the "is" would be this part?:

```
     The follow activity
      generally is a request to see the objects a user creates, this
      would make the "followers" collection a good default collection
      to provide to the user when selecting the audience targetting.
```

This seems totally consistent with the later MAY.

If this was about a separate section I've missed, feel free to reopen!
