### ISSUE TITLE
Don't dereference groups to all users

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#52]
originally: https://hypothes.is/a/k6fU5GM3SLeDOo6UatskDA

> If the entry is a collection, then the server must dereference the collection (with the user's credentials) and add each person in the collection to the list of recipients for the message.

What if there are 1 million people in the Collection? Why not just delivery the inbox of the group?

We have this problem in real world (where group is all users of cnn.com following 'world news') and do something like the above.

**Comment by cwebber** [comment]
Yes, assuming I'm reading this correctly, this doesn't make sense... the "Public" group can't be expanded, and "Followers" aren't ever in Pump.io at least.

**Comment by tsyesika** [comment]
This is only for delivery, this isn't for creation of the activity. We should clarify what we mean: When performing delivery of an activity to its recipients, you must dereference the collection and deliver the activity to each recipient individually, the activity however still references the collection in the audience targeting properties.
