### ISSUE TITLE
Clarify use of 'objectTypes'

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#53]
orig: https://hypothes.is/a/XjLces6UQ-aKuuS2iLFUfA

> The streams nomencluture is applied to any collection comprosed purely of activities. These objects should be so declared using the objectTypes property:

the following example as "itemsType", but I don't see that defined in this document or AS Core/Vocab

**Comment by rhiaro** [comment]
Is objectTypes _required_? This sounds like it prevents a stream of different types of activities, which seems like kind of a handicap. Maybe we just don't mention this, and it can be used according to ActivityStreams if the implementer so desires to restrict items in a stream to a single type.

**Comment by cwebber** [comment]
Yeah I have no idea what this itemsType / objectTypes stuff is.  I'm not sure it's actually useful to declare a specific type for a set of objects ahead of time... what would it do?

I'm going to remove the text, but if someone can explain what it means and why it's needed , we can add it back.

**Comment by cwebber** [comment]
As of 676a70d, the definition of "streams" is greatly simplified.  If I did something wrong, happy to adjust.  Otherwise, closing!
