### ISSUE TITLE
Clarify "prohom authorization" (typo?)

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#55]
orig: https://hypothes.is/a/8qOPzBsFS6-e4rnD439s_g

> Once the complete list of recipients has been determined, the server must then deliver the activity to each recipient. For a federated implementation, this must be done by performing a HTTP POST, with prohom authorization as the submitting user, of the submitted activity body to the URI of the inbox collection of each recipient

typo? I can't tell what that was supposed to be though (to send a PR)

**Comment by cwebber** [comment]
I have no idea what that word was either.  At any rate, it works without the word, so I cut it out.  Thanks for noticing!
