### ISSUE TITLE
Move authorization and authentication to a security considerations section

### ISSUE THREAD

**Issue by evanp** [w3c-social/activitypub#60]

**Comment by cwebber** [comment]
Should we move information to the security considerations section even if it ties in with another section more fluidly?  Honest question, I don't have experience doing spec writing here.

**Comment by akuckartz** [comment]
@cwebber In such a situation you can point to that section from the security considerations section.

**Comment by cwebber** [comment]
@akuckartz Ok, thanks!

**Comment by rpeinl** [comment]
see #77

**Comment by cwebber** [comment]
I added a security considerations section referencing this in a5d1de1.
