### ISSUE TITLE
Add Example activities of each type in sec 9.2 "Activities"

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#61]
This will make it more clear what properties are allowed. For example, should CreateActivity.object.id be specified?

https://github.com/w3c-social/activitypump/issues/56#issuecomment-163767421

Official examples will also be invaluable for any test suite.

**Comment by tsyesika** [comment]
We should explain the side-effects (see #31) of each activity however I don't think we need to duplicate the examples of the activities that already exist in activity streams 2.0 vocab spec.
